# -*- coding: utf-8 -*-
"""Infosys.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jFc4TtZPo5whH9fGKeGgvsmWw_yJ_t9a

**NUMPY**
"""

import numpy as np
n1 = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(n1)
print(n1[0])
print(n1[1:4])
print(n1[:4])
print(n1[3:])

"""*MEAN*"""

import numpy as np
n1=np.array([10,20,30,40,50,60])
np.mean(n1)

"""MEDIAN"""

import numpy as np
n1=np.array([10,20,30,40,50,60])
np.median(n1)

"""Standard deviation"""

import numpy as np
n1=np.array([10,20,30,40,50,60])
np.std(n1)

"""Basic addition"""

import numpy as np
ni=np.array([10,20,30])
n1=n1+1
n1

"""basic multiplication"""

import numpy as np
n1=np.array([10,20,30])
n= n1 * 2
n1

"""Basic subtraction"""

import numpy as np
n1=np.array([10,20,30])
n= n1 - 2
n1

"""Basic Divison"""

import numpy as np
n1=np.array([10,20,30])
n= n1/2
n1

"""Addition of numpy arrays"""

import numpy as np
n1=np.array([10,20])
n2=np.array([30,40])

np.sum([n1,n2],axis =0 )

np.sum([n1,n2],axis=1)

"""Single-dimensional
Array
"""

import numpy as np
n1=np.array([10,20,30,40])
n1

"""Multi-dimensional
Array

"""

import numpy as np
n2=np.array([[10,20,30,40],[40,30,20,10]])
n2

"""Initializing NumPy array within a range

"""

import numpy as up
n1=np.arange(10,20)
n1

import numpy as np
n1=np.arange (10,50,5)
n1

"""column_stack()

"""

import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.column_stack((n1,n2))

"""vstack()"""

import numpy as np
n1=np.array ([10,20,30])
n2=np.array([40,50,60])
np.vstack((n1,n2))

"""hstack()

"""

import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.hstack((n1,n2))

"""Checking the shape of NumPy arrays"""

import numpy as np
n1=np.array([[1,2,3], [4,5,6]])
n1.shape

"""INITIALIZING NUMPY ARRAY

"""

import numpy as np
n1=np.random.randint(1,100,5)
n1

import numpy as np
n1 = np.full((2,2),10)
print(n1)

n1 = np.zeros((1,2))
print(n1)

n1 = np.zeros((5,5))
print(n1)

"""Extracting Individual Elements

"""

import pandas as pd
s1 =pd.Series ([1,2,3,4,5,6,7,8,9])
s1[3]

s2 = pd.Series ([1,2,3,4,5,6,7,8,9])
s2[:4]

s3 = pd.Series ([1,2,3,4,5,6,7,8,9])
s3[-3:]

import pandas as pd
pd.Series({'a':10,'b':20,'c':30},index=['b','c','d','a'])

"""Series Object from Dictionary"""

import pandas as pd
pd.Series({'a':10, 'b':20,'c':30})

"""CHANGING INDEX"""

import pandas as pd
s1=pd.Series([1,2,3,4,5])
print(s1)
s2=pd.Series ([1,2,3,4,5],index=['a','b','c','d','e'])
print(s2 )

"""Pandas Series Object

"""

import pandas as pd
s1=pd.Series([1,2,3,4,5])
s1

n1= np.array([[1,2,3],[4,5,6], [7,8,9]])
n1

n2= np.array([[9,8,7],[6,5,4],[3,2,1]])
 n2

n1.transpose()

"""BOX PLOT"""

one = [1,2,3,4,5,6,7,8,9]
two = [1,2,3,4,5,4,3,2,1]
three = [6,7,8,9,8,7,6,5,4]
data= list([one,two,three])

one = [1,2,3,4,5,6,7,8,9]
two = [1,2,3,4,5,4,3,2,1]
three = [6,7,8,9,8,7,6,5,4]
data = list([one,two,three])

import pandas as pd

path = '/kaggle/input/iriscsv/Iris.csv'
print(":", path)
iris = pd.read_csv(path)
display(iris.head())

import matplotlib.pyplot as plt
plt.hist(iris['SepalLengthCm'],bins=30,color="r")
plt.show()

import matplotlib.pyplot as plt
plt.hist(data,color=["g", "b", "orange"], bins=4)
plt.show()

"""HISTOGRAM"""

data = [1,3,3,3,3,9,9,5,4,4,8,8,8,6,7]
plt.hist(data)
plt.show()

x=[10,20,30,40,50,60,70,80,90]
a=[8,1,7,2,0,3,7,3,2]
b=[7,2,5,6,9,1,4,5,3]
plt.subplot(1,2,1)
plt.scatter(x,a,marker="*",c="g", s=100)
plt.subplot(1,2,2)
plt.scatter(x,b,marker=".", c="r", s=200)
plt.show()

"""Scatter Plot"""

import matplotlib.pyplot as plt
x=[10,20,30,40,50,60,70,80,90]
a=[8,1,7,2,0,3,7,3,2]
b=[7,2,5,6,9,1,4,5,3]
plt.scatter(x,a,marker="*",c="g", s=100)
plt.scatter(x,b,marker=".", c="r", s=200)
plt.show()

import matplotlib.pyplot as plt
x=[10,20,30,40,50,60,70,80,90]
a=[8,1,7,2,0,3,7,3,2]
plt.scatter(x,a,marker="*",c="g",s=100)
plt.show()

x=[10,20,30,40,50,60,70,80,90]
a=[8,1,7,2,0,3,7,3,2]
plt.scatter(x,a)
plt.show()

import matplotlib.pyplot as plt
names = ['A', 'B', 'C', 'D']
values = [10, 25, 15, 30]
plt.barh(names, values, color='g')
plt.title("Bar Plot")
plt.xlabel("Names")
plt.ylabel("Marks")
plt.grid(True)
plt.show()

plt.bar(names, values)
plt.title("Bar Plot")
plt.xlabel("Names")
plt.ylabel("Marks")
plt.grid(True)
plt.show()

student = {"Bob":87,"Matt":56,"Sam":27}
names = list(student.keys())
values = list(student.values())
plt.bar(names, values)
plt.show()

x=np.arange(1,11)
y1=2*x
y2=3*x
plt.subplot(1,2,1)
plt.plot(x,y1,color='g',linestyle=':', linewidth=2)
plt.subplot(1,2,2)
plt.plot(x, y2, color='r', linestyle=':', linewidth=2)
plt.show()

import matplotlib.pyplot as plt
x=np.arange(1,11)
y1=2*x
y2=3*x
plt.plot(x,y1,color='g', linestyle=':', linewidth=2)
plt.plot(x,y2,color='r', linestyle='-', linewidth=3)
plt.title("Line Plot")
plt.xlabel("x-axis")
plt.ylabel("y-axis")
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.arange(1, 11)
y = 2 * x

plt.plot(x, y, color='blue', linestyle='-', linewidth=2)
plt.show()

plt.plot(x,y)
plt.title("Line Plot")
plt.xlabel("x-label")
plt.ylabel("y-label")
plt.show()

import numpy as np
from matplotlib import pyplot as plt

x=np.arange(1,11)
y= 2*x

plt.plot(x,y)
plt.show()

import pandas as pd
path = '/kaggle/input/iriscsv/Iris.csv'
iris = pd.read_csv(path)
display(iris._get_numeric_data().mean())
display(iris._get_numeric_data().median())
display(iris._get_numeric_data().min())
display(iris._get_numeric_data().max())

iris.drop([1,2,3],axis=0)

iris.loc[0:3, ("SepalLengthCm", "PetalLengthCm")]

iris.drop('SepalLengthCm', axis=1)

iris.iloc[0:3, 0:2]

iris.shape

iris.tail(10)

iris.tail()

iris.head(20)

iris.head()

import pandas as pd
df=pd.DataFrame({"Name": ["Sam", "Anne","Jennifer"], "Marks": [50,60,70]})
df

type(df)

iris = pd.read_csv('/kaggle/input/iriscsv/Iris.csv')

iris.head()

import pandas as pd
pd.DataFrame ({"Name": ['Bob','Sam','Anne'],"Marks":[76,25,92]})

import pandas as pd
s1 = pd.Series([1, 2, 3, 4, 5])
s1 + 5
s2 = pd.Series([10, 20, 30, 40, 50, 60, 70, 80, 90])

import seaborn as sns
from matplotlib import pyplot as plt

fmri = sns.load_dataset("fmri")
fmri.head()

import seaborn as sns
import matplotlib.pyplot as plt

sns.lineplot(x="timepoint", y="signal", data=fmri)
plt.show()

"""DOUGHNUT CHART

"""

import matplotlib.pyplot as plt

fruit = ['Apple', 'Orange', 'Mango', 'Guava']
quantity = [67,34,100,29]
plt.pie(quantity, labels=fruit, radius=2)
plt.pie([1],colors=['w'],radius=1)
plt.show()

"""Pie-Chart"""

import matplotlib.pyplot as plt

fruit = ['Apple', 'Orange', 'Mango', 'Guava']
quantity = [67, 34, 100, 29]

plt.pie(quantity, labels=fruit)
plt.show()

"""Violin-Plot"""

one= [1,2,3,4,5,6,7,8,9]
two = [1,2,3,4,5,4,3,2,1]
three= [6,7,8,9,8,7,6,5,4]
data= list([one,two,three])
plt.violinplot (data, showmedians=True)
plt.show()

# seaborn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# Visualizing statistical relationships
ds = sns.load_dataset('tips')

ds = sns.load_dataset('tips')
ds.head()

ds.shape

sns.relplot(data=ds,x='total_bill',y='tip',hue='smoker', style='smoker')

sns.relplot(
data=ds,
x="total_bill", y="tip", hue="smoker", style="time"
)

sns.relplot(
data=ds, x="total_bill", y="tip", hue="size")

# prevent from overlapping (swarm plot)
sns.catplot(data=ds, x='day', y='total_bill', kind='swarm')

sns.catplot(data=ds,x='day',y='total_bill',jitter=False)

sns.relplot(
data=fmri,kind='line',
x='timepoint', y='signal',
hue='region', style='event',
dashes=False, markers=True
)

sns.relplot(
data=fmri, kind='line',
x='timepoint',y='signal',
hue='region',style='event'
)

sns.relplot(
data=fmri,kind='line',
x='timepoint',y='signal',
hue='event')

sns.relplot(
data=fmri,kind='line',
x='timepoint', y='signal',errorbar=None
)

sns.relplot(data=fmri,x='timepoint',y='signal',kind='line')

fmri.shape
sns.relplot(data=fmri, x='timepoint',y='signal')

sns.catplot(data=ds,x='day',y='total_bill', hue='sex',kind='swarm')

sns.catplot(data=ds,x='smoker',y='tip',order=['No', 'Yes'])

sns.catplot(data=ds,x='total_bill',y='day',hue='time',kind='swarm')

sns.catplot (data=ds,x='day',y='total_bill', kind='box')

sns.catplot(data=ds,x='total_bill',y='day',hue='sex',kind='violin')

sns.catplot(data=ds,x='day',y='total_bill', hue='sex',kind='violin', split=True)
